- name: Create new users
  hosts: all
  tasks:
     - name: Add the atpm user jack
       user:
         name: jack
         comment: jack
         
     - name: Add the atpm user ken
       user:
         name: kenneth
         comment: kenneth

     - name: Add the atpm user miuel
       user:         
         name: miguel
         comment: miguel  
